=== open-design-systems/open-design-systems.github.io/apps/www/open-design-system-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Design System",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Automatically generated unique identifier for each item."
    },
    "meta": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      },
      "required": ["name", "description"]
    },
    "colors": {
      "type": "object",
      "properties": {},
      "patternProperties": {
        ".*": {
          "type": "object",
          "properties": {
            "meta": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "Automatically generated unique identifier for each item."
                },
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                }
              },
              "required": ["name", "description"]
            },
            "light": {
              "type": "object",
              "properties": {
                "hex": {
                  "type": "string",
                  "pattern": "^#(?:[0-9a-fA-F]{3,4}){1,2}$"
                },
                "rgba": {
                  "type": "object",
                  "properties": {
                    "red": {
                      "type": "string"
                    },
                    "green": {
                      "type": "string"
                    },
                    "blue": {
                      "type": "string"
                    },
                    "alpha": {
                      "type": "string"
                    }
                  }
                }
              },
              "required": ["hex", "rgba"]
            },
            "dark": {
              "type": "object",
              "properties": {
                "hex": {
                  "type": "string",
                  "pattern": "^#(?:[0-9a-fA-F]{3,4}){1,2}$"
                },
                "rgba": {
                  "type": "object",
                  "properties": {
                    "red": {
                      "type": "string"
                    },
                    "green": {
                      "type": "string"
                    },
                    "blue": {
                      "type": "string"
                    },
                    "alpha": {
                      "type": "string"
                    }
                  }
                }
              },
              "required": ["hex", "rgba"]
            }
          },
          "required": ["meta", "light", "dark"]
        }
      },
      "additionalProperties": true
    },
    "typography": {
      "type": "object",
      "properties": {},
      "patternProperties": {
        ".*": {
          "type": "object",
          "properties": {
            "meta": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "Automatically generated unique identifier for each item."
                },
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                }
              },
              "required": ["name", "description"]
            },
            "fontFamily": {
              "type": "string"
            },
            "fontSize": {
              "type": "string"
            },
            "fontWeight": {
              "type": "string"
            },
            "lineHeight": {
              "type": "string"
            },
            "letterSpacing": {
              "type": "string"
            }
          },
          "required": [
            "meta",
            "fontFamily",
            "fontSize",
            "fontWeight",
            "lineHeight",
            "letterSpacing"
          ]
        }
      },
      "additionalProperties": true
    },
    "spacing": {
      "type": "object",
      "properties": {},
      "patternProperties": {
        ".*": {
          "type": "object",
          "properties": {
            "meta": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "Automatically generated unique identifier for each item."
                },
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                }
              },
              "required": ["name", "description"]
            },
            "value": {
              "type": "number"
            }
          },
          "required": ["meta", "value"]
        }
      },
      "additionalProperties": true
    },
    "surface": {
      "type": "object",
      "properties": {},
      "patternProperties": {
        ".*": {
          "type": "object",
          "properties": {
            "meta": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "Automatically generated unique identifier for each item."
                },
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                }
              },
              "required": ["name", "description"]
            },
            "borderColor": {
              "type": "string"
            },
            "borderRadius": {
              "type": "number"
            },
            "borderWidth": {
              "type": "number"
            },
            "boxShadow": {
              "type": "string"
            },
            "backgroundColor": {
              "type": "string"
            }
          },
          "required": [
            "meta",
            "borderColor",
            "borderRadius",
            "borderWidth",
            "boxShadow",
            "backgroundColor"
          ]
        }
      }
    },
    "shadows": {
      "type": "object",
      "properties": {},
      "patternProperties": {
        ".*": {
          "type": "object",
          "properties": {
            "meta": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "Automatically generated unique identifier for each item."
                },
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                }
              },
              "required": ["name", "description"]
            },
            "elevation": {
              "type": "string"
            },
            "shadowColor": {
              "type": "string"
            },
            "shadowOpacity": {
              "type": "number"
            },
            "shadowOffset": {
              "type": "object",
              "properties": {
                "width": {
                  "type": "number"
                },
                "height": {
                  "type": "number"
                }
              }
            },
            "shadowRadius": {
              "type": "number"
            }
          },
          "required": [
            "meta",
            "elevation",
            "shadowColor",
            "shadowOpacity",
            "shadowOffset",
            "shadowRadius"
          ]
        }
      },
      "additionalProperties": true
    },
    "primitives": {
      "type": "object",
      "properties": {},
      "patternProperties": {
        ".*": {
          "type": "object",
          "properties": {
            "meta": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "description": "Automatically generated unique identifier for each item."
                },
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                }
              },
              "required": ["name", "description"]
            },
            "type": {
              "type": "string",
              "enum": ["button", "text"]
            },
            "surfaceId": {
              "type": "string"
            },
            "typographyId": {
              "type": "string"
            },
            "spacingId": {
              "type": "string"
            }
          },
          "required": ["meta", "type"],
          "if": {
            "properties": {
              "type": { "const": "button" }
            }
          },
          "then": {
            "required": ["surfaceId", "typographyId", "spacingId"]
          },
          "else": {
            "required": ["typographyId"]
          }
        }
      },
      "additionalProperties": true
    }
  },
  "required": [
    "id",
    "meta",
    "colors",
    "typography",
    "spacing",
    "surface",
    "shadows",
    "primitives"
  ]
}

=== open-design-systems/open-design-systems.github.io/apps/www/src/components/design-system-builder/templates/open-design-system.json
{
  "$schema": "../../../../open-design-system-schema.json",
  "id": "default-system",
  "meta": {
    "name": "Default Design System",
    "description": "A basic design system with default values based on Material Design."
  },
  "colors": {
    "primary": {
      "meta": {
        "id": "colors.primary",
        "name": "primary",
        "description": ""
      },
      "light": {
        "hex": "#6200ea",
        "rgba": {
          "red": "98",
          "green": "0",
          "blue": "234",
          "alpha": "255"
        }
      },
      "dark": {
        "hex": "#3700b3",
        "rgba": {
          "red": "55",
          "green": "0",
          "blue": "179",
          "alpha": "255"
        }
      }
    },
    "secondary": {
      "meta": {
        "id": "colors.secondary",
        "name": "secondary",
        "description": ""
      },
      "light": {
        "hex": "#03dac6",
        "rgba": {
          "red": "3",
          "green": "218",
          "blue": "198",
          "alpha": "255"
        }
      },
      "dark": {
        "hex": "#018786",
        "rgba": {
          "red": "1",
          "green": "135",
          "blue": "134",
          "alpha": "255"
        }
      }
    },
    "background": {
      "meta": {
        "id": "colors.background",
        "name": "background",
        "description": ""
      },
      "light": {
        "hex": "#121212",
        "rgba": {
          "red": "18",
          "green": "18",
          "blue": "18",
          "alpha": "255"
        }
      },
      "dark": {
        "hex": "#ffffff",
        "rgba": {
          "red": "0",
          "green": "0",
          "blue": "0",
          "alpha": "255"
        }
      }
    }
  },
  "typography": {
    "body": {
      "meta": {
        "id": "typography.body",
        "name": "body",
        "description": ""
      },
      "fontFamily": "Roboto",
      "fontSize": "16",
      "fontWeight": "400",
      "lineHeight": "1.5",
      "letterSpacing": "0.5"
    },
    "heading": {
      "meta": {
        "id": "typography.heading",
        "name": "heading",
        "description": ""
      },
      "fontFamily": "Oswald",
      "fontSize": "24",
      "fontWeight": "700",
      "lineHeight": "1.3",
      "letterSpacing": "0.2"
    }
  },
  "spacing": {
    "xs": {
      "meta": {
        "id": "spacing.xs",
        "name": "xs",
        "description": ""
      },
      "value": 4
    },
    "sm": {
      "meta": {
        "id": "spacing.sm",
        "name": "sm",
        "description": ""
      },
      "value": 8
    },
    "md": {
      "meta": {
        "id": "spacing.md",
        "name": "md",
        "description": ""
      },
      "value": 16
    },
    "lg": {
      "meta": {
        "id": "spacing.lg",
        "name": "lg",
        "description": ""
      },
      "value": 24
    },
    "xl": {
      "meta": {
        "id": "spacing.xl",
        "name": "xl",
        "description": ""
      },
      "value": 32
    }
  },
  "surface": {
    "box": {
      "meta": {
        "id": "surface.box",
        "name": "box",
        "description": ""
      },
      "borderColor": "colors.background",
      "borderRadius": 5,
      "borderWidth": 1,
      "boxShadow": "inset",
      "backgroundColor": "colors.background"
    }
  },
  "shadows": {
    "elevation1": {
      "meta": {
        "id": "shadows.elevation1",
        "name": "elevation1",
        "description": ""
      },
      "elevation": "1dp",
      "shadowColor": "colors.primary",
      "shadowOpacity": 0.1,
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 1.0
    },
    "elevation2": {
      "meta": {
        "id": "shadows.elevation2",
        "name": "elevation2",
        "description": ""
      },
      "elevation": "2dp",
      "shadowColor": "colors.primary",
      "shadowOpacity": 0.2,
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowRadius": 2.0
    }
  },
  "primitives": {
    "button": {
      "type": "button",
      "meta": {
        "id": "b1",
        "name": "primary",
        "description": ""
      },
      "spacingId": "spacing.md",
      "surfaceId": "surface.box",
      "typographyId": "typography.body"
    }
  }
}
